name: IMLO
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.11
  - numpy=1.26.4
  - pandas
  - matplotlib
  - scikit-learn
  - tqdm
  - pip
  - pip:
      - torch==2.2.0
      - torchvision==0.17.0
